#include <stmt/assign.hpp>
#include <stmt/exec_func.hpp>
#include <stmt/for_iterator.hpp>
#include <stmt/for_range.hpp>
#include <stmt/funcdef.hpp>
#include <stmt/if.hpp>
#include <stmt/mcl.hpp>
#include <stmt/put.hpp>
#include <stmt/while.hpp>